### ISSUE TITLE
在 DumpGraphic 時會產生 Panic

### ISSUE THREAD

**Issue by chivincent** [x-gate/xgtool#7]
## Version

軟體版本：1.0.0
執行平台：Windows 11 (AMD64)

## Description

在執行 `.\xgtool dump-graphic` 指令時會產生一大堆 panic 訊息，且 `output/` 生成的圖片並不完整

### Log

```
goroutine 12879 [runnable, locked to thread]:
runtime.cgocall(0x979ac0, 0xc0149576c8)
        /usr/local/go/src/runtime/cgocall.go:157 +0x3e fp=0xc017e65c78 sp=0xc017e65c40 pc=0x914fbe
syscall.SyscallN(0x9e86fd?, {0xc017e65d10?, 0xc017e65d88?, 0x9890d4?})
        /usr/local/go/src/runtime/syscall_windows.go:544 +0x107 fp=0xc017e65cf0 sp=0xc017e65c78 pc=0x975067
syscall.Syscall9(0x1?, 0xc0157c8540?, 0xc017e65de0?, 0x987965?, 0xc017ea3b78?, 0x11?, 0xc0157c8540?, 0xffffffffffffffff?, 0x0?, 0x0, ...)
        /usr/local/go/src/runtime/syscall_windows.go:494 +0x72 fp=0xc017e65d68 sp=0xc017e65cf0 pc=0x974f52
syscall.CreateFile(0xc017ea3b78?, 0x40000000, 0x3, 0x1?, 0x4, 0x80, 0x0)
        /usr/local/go/src/syscall/zsyscall_windows.go:507 +0xb2 fp=0xc017e65df0 sp=0xc017e65d68 pc=0x98a472
syscall.Open({0xc017ea3b78?, 0x98438a?}, 0x80041, 0x1a4)
        /usr/local/go/src/syscall/syscall_windows.go:412 +0x288 fp=0xc017e65e70 sp=0xc017e65df0 pc=0x9881c8
os.openFileNolog({0xc017ea3b78, 0x11}, 0x41, 0x1a4)
        /usr/local/go/src/os/file_windows.go:172 +0x119 fp=0xc017e65ef0 sp=0xc017e65e70 pc=0x9e0f19
os.OpenFile({0xc017ea3b78, 0x11}, 0x41, 0x2?)
        /usr/local/go/src/os/file.go:334 +0x3e fp=0xc017e65f28 sp=0xc017e65ef0 pc=0x9e00de
xgtool/cmd/dumpgraphic.dumpGraphic.func1()
        /github/workspace/cmd/dumpgraphic/root.go:108 +0x197 fp=0xc017e65fe0 sp=0xc017e65f28 pc=0xaabf37
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc017e65fe8 sp=0xc017e65fe0 pc=0x9782e1
created by xgtool/cmd/dumpgraphic.dumpGraphic in goroutine 1
        /github/workspace/cmd/dumpgraphic/root.go:94 +0x1d2

goroutine 12891 [runnable]:
xgtool/cmd/dumpgraphic.dumpGraphic.func1()
        /github/workspace/cmd/dumpgraphic/root.go:94 fp=0xc017f5bfe0 sp=0xc017f5bfd8 pc=0xaabda0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc017f5bfe8 sp=0xc017f5bfe0 pc=0x9782e1
created by xgtool/cmd/dumpgraphic.dumpGraphic in goroutine 1
        /github/workspace/cmd/dumpgraphic/root.go:94 +0x1d2
```

## 可能原因及解決方法

在 [syscall_windows.go](https://go.dev/src/syscall/syscall_windows.go#L542) 中表示會使用 `GetCurrentDirectory`，根據[官方文件](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getcurrentdirectory) 中的描述：

> Multithreaded applications and shared library code should not use the
GetCurrentDirectory function and should avoid using relative path names. The current directory state written by the [SetCurrentDirectory](https://learn.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-setcurrentdirectory) function is stored as a global variable in each process, therefore multithreaded applications cannot reliably use this value without possible data corruption from other threads that may also be reading or setting this value. This limitation also applies to the SetCurrentDirectory and [GetFullPathName](https://learn.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-getfullpathnamea) functions. The exception being when the application is guaranteed to be running in a single thread, for example parsing file names from the command line argument string in the main thread prior to creating any additional threads. Using relative path names in multithreaded applications or shared library code can yield unpredictable results and is not supported.

可能要考慮將  Windows 平台的檔案輸出以另外一種方式達成

**Comment by chivincent** [comment]
經過 #10 的修正，看起來狀況並沒有改善，需要再另外釐清 Windows 平台上無法成功匯出圖片的原因
